plugins {
    id "com.android.application"
}
android {
    namespace "com.exgame.app"
    compileSdk 34
    defaultConfig {
        applicationId "com.exgame.app"
        minSdk 24
        targetSdk 34
        versionCode 126
        versionName "0.1.26"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
        debug { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "androidx.webkit:webkit:1.11.0"
}
